export interface OrigamiInfo {
  id: number;
  name: string;
  picFolderName: string;
  author: string;
  date: Date;
  lastModifiedDate: string;
  heightWidthRatio: number;
  imagesCount: number;
  description?: string;
}

export interface PositionedOrigami extends OrigamiInfo {
  top: number;
  left: number;
}

export const ORIGAMI_INFO_ARRAY = [
  {
    id: 1,
    name: "Deer and Fawn",
    picFolderName: "deer_and_fawn",
    author: "John Montroll, Stephen Weiss",
    date: new Date(2019, 5, 19),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.74,
    imagesCount: 1,
  },
  {
    id: 2,
    name: "Pegasus",
    picFolderName: "pegasus",
    author: "Dong Viet Thien",
    date: new Date(2019, 5, 25),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 4,
    description:
      "Thought this wingèd fold as\nMy greatest work at that time—\nTime did change my mind",
  },
  {
    id: 3,
    name: "Owl",
    picFolderName: "owl",
    author: "Para Nicolas",
    date: new Date(2019, 5, 27),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 4,
    name: "Sea Turtle & Zebra",
    picFolderName: "turtle_and_zebra",
    author: "Won Park, Kawahata Fumiaki",
    date: new Date(2019, 5, 30),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
    description:
      "Reminded the tale\nof Chelone from Greek myth—\nI was lazy too",
  },
  {
    id: 5,
    name: "Flying Eagle",
    picFolderName: "flying_eagle",
    author: "Zhou Xian Zong",
    date: new Date(2019, 6, 6),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 2,
  },
  {
    id: 6,
    name: "Penguin",
    picFolderName: "penguin",
    author: "Yoo Tae Yong",
    date: new Date(2019, 6, 7),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 7,
    name: "Fighter Jets",
    picFolderName: "fighter_jets",
    author: "Won Park, Yoshihisa Kimura, Elmer A. Norvell",
    date: new Date(2019, 6, 10),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 2,
  },
  {
    id: 8,
    name: "Coelophysis",
    picFolderName: "coelophysis",
    author: "Kamiya Satoshi",
    date: new Date(2019, 6, 11),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.84,
    imagesCount: 2,
  },
  {
    id: 9,
    name: "Baby Parrot",
    picFolderName: "baby_parrot",
    author: "Riccardo Foschi",
    date: new Date(2019, 6, 27),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 2,
  },
  {
    id: 10,
    name: "Ant",
    picFolderName: "ant",
    author: "Piotr Pluta",
    date: new Date(2019, 6, 28),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 4,
  },
  {
    id: 11,
    name: "Zero Fighter Plane",
    picFolderName: "zero_fighter_plane",
    author: "Won Park",
    date: new Date(2019, 7, 4),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.76,
    imagesCount: 5,
  },
  {
    id: 12,
    name: "Woman",
    picFolderName: "woman",
    author: "Sriram V",
    date: new Date(2019, 7, 7),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 4,
  },
  {
    id: 13,
    name: "Night Fury",
    picFolderName: "night_fury",
    author: "Saku B",
    date: new Date(2019, 7, 12),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 3,
    description:
      "Unholy offspring\nof Lightning and Death itself—\nmy terrible fold",
  },
  {
    id: 14,
    name: "Man",
    picFolderName: "man",
    author: "Sriram V",
    date: new Date(2019, 7, 16),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 3,
  },
  {
    id: 15,
    name: "Man & Woman",
    picFolderName: "man_and_woman",
    author: "Sriram V",
    date: new Date(2019, 7, 18),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 16,
    name: "Rooster",
    picFolderName: "rooster",
    author: "Hagiwara Gen",
    date: new Date(2019, 7, 25),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 3,
  },
  {
    id: 17,
    name: "Daedalus",
    picFolderName: "daedalus",
    author: "Tran Trung Hieu",
    date: new Date(2019, 8, 1),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
    description:
      "The mortal who flew\nin the age of Greek gods— proud\nto fold Daedalus",
  },
  {
    id: 18,
    name: "Peacock",
    picFolderName: "peacock",
    author: "Jun Maekawa",
    date: new Date(2019, 8, 1),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 3,
    description:
      "Folded this three times,\nas a request from maidens— \nnot sure what it holds",
  },
  {
    id: 19,
    name: "Mammoth",
    picFolderName: "mammoth",
    author: "Crease Lightning Origami",
    date: new Date(2019, 8, 2),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.85,
    imagesCount: 1,
  },
  {
    id: 20,
    name: "Dragon",
    picFolderName: "dragon",
    author: "Miyamoto Chuya",
    date: new Date(2019, 8, 8),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.83,
    imagesCount: 4,
  },
  {
    id: 21,
    name: "Robin",
    picFolderName: "robin",
    author: "Winston Lee",
    date: new Date(2019, 8, 9),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 4,
  },
  {
    id: 22,
    name: "Rhinoceros",
    picFolderName: "rhino",
    author: "Ta Trung Dong",
    date: new Date(2019, 8, 13),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 3,
  },
  {
    id: 23,
    name: "Lion",
    picFolderName: "lion",
    author: "Beth Johnson",
    date: new Date(2019, 8, 26),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 2,
  },
  {
    id: 24,
    name: "Unicorn",
    picFolderName: "unicorn",
    author: "Roman Diaz",
    date: new Date(2019, 8, 29),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.85,
    imagesCount: 2,
  },
  {
    id: 25,
    name: "T-Rex",
    picFolderName: "t-rex",
    author: "Park Jong Woo",
    date: new Date(2019, 9, 3),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 5,
  },
  {
    id: 26,
    name: "Horse",
    picFolderName: "horse",
    author: "Jeong Jae Il",
    date: new Date(2019, 9, 6),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 7,
    description:
      "In Greek myth, the god\nPoseidon created them— \nbut I folded this",
  },
  {
    id: 27,
    name: "Hippocampus",
    picFolderName: "hippocampus",
    author: "Roman Diaz",
    date: new Date(2019, 9, 8),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 2,
  },
  {
    id: 28,
    name: "Horses Lineup",
    picFolderName: "horses_lineup",
    author: "Dong Viet Thien, Roman Diaz, Jeong Jae Il",
    date: new Date(2019, 9, 8),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 1,
  },
  {
    id: 29,
    name: "Giraffe",
    picFolderName: "giraffe",
    author: "John Montroll",
    date: new Date(2019, 9, 13),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 5,
  },
  {
    id: 30,
    name: "Phoenix",
    picFolderName: "phoenix",
    author: "John Montroll",
    date: new Date(2019, 9, 13),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 5,
    description:
      "The blazing bird dies\nand rises from ashes again— \nloneliness remains",
  },
  {
    id: 31,
    name: "Mammoth",
    picFolderName: "mammoth_2",
    author: "Miyajima Noboru",
    date: new Date(2019, 9, 26),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 6,
  },
  {
    id: 32,
    name: "Smilodon",
    picFolderName: "smilodon",
    author: "Kamiya Satoshi",
    date: new Date(2019, 9, 28),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 6,
  },
  {
    id: 33,
    name: "Polar Bear",
    picFolderName: "polar_bear",
    author: "Gerard Ty Sovann",
    date: new Date(2019, 10, 3),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.8,
    imagesCount: 5,
  },
  {
    id: 34,
    name: "Boats Lineup",
    picFolderName: "boats_lineup",
    author: "Traditional, Hadi Tahir",
    date: new Date(2019, 10, 11),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 10,
  },
  {
    id: 35,
    name: "Money Turtle",
    picFolderName: "tortoise",
    author: "Lo Yu",
    date: new Date(2019, 10, 17),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 4,
  },
  {
    id: 36,
    name: "Sail Boat & Fox",
    picFolderName: "fox",
    author: "Hadi Tahir, Yoo Tae Yong",
    date: new Date(2019, 11, 1),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.83,
    imagesCount: 1,
  },
  {
    id: 37,
    name: "Dolphin",
    picFolderName: "dolphin",
    author: "Kawahata Fumiaki",
    date: new Date(2019, 11, 8),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 8,
  },
  {
    id: 38,
    name: "Rabbit",
    picFolderName: "rabbit",
    author: "Richard Galindo",
    date: new Date(2019, 11, 15),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 2,
  },
  {
    id: 39,
    name: "Reindeer & Sleigh",
    picFolderName: "reindeer_and_sleigh",
    author: "Kamiya Satoshi, Taon",
    date: new Date(2019, 11, 25),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 10,
  },
  {
    id: 40,
    name: "Reindeer",
    picFolderName: "reindeer",
    author: "Kamiya Satoshi",
    date: new Date(2019, 11, 29),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 6,
  },
  {
    id: 41,
    name: "Brown Grouper Fish",
    picFolderName: "brown_grouper_fish",
    author: "Gerard Ty Sovann",
    date: new Date(2020, 1, 9),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 42,
    name: "Fish",
    picFolderName: "fish",
    author: "Eric Joisel",
    date: new Date(2020, 1, 9),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 43,
    name: "Valentine",
    picFolderName: "heart_with_arrow",
    author: "Robert J. Lang",
    date: new Date(2020, 1, 14),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.83,
    imagesCount: 1,
  },
  {
    id: 44,
    name: "Winged Heart",
    picFolderName: "heart_with_wings",
    author: "Phong Tran",
    date: new Date(2020, 1, 14),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.83,
    imagesCount: 1,
  },
  {
    id: 45,
    name: "Heart With Musical Note",
    picFolderName: "heart_with_music",
    author: "Christophe Michel",
    date: new Date(2020, 1, 14),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.83,
    imagesCount: 1,
  },
  {
    id: 46,
    name: "Devil's Wing Heart",
    picFolderName: "heart_with_bat_wings",
    author: "Phong Tran",
    date: new Date(2020, 1, 14),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.83,
    imagesCount: 1,
  },
  {
    id: 47,
    name: "Puffy Heart",
    picFolderName: "heart",
    author: "Paper Kawaii",
    date: new Date(2020, 1, 14),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 2,
  },
  {
    id: 48,
    name: "I ♥ U",
    picFolderName: "i_love_u",
    author: "Jeremy Shafer",
    date: new Date(2020, 1, 14),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.83,
    imagesCount: 1,
  },
  {
    id: 49,
    name: "Goat Fish",
    picFolderName: "goat_fish",
    author: "Robert J. Lang",
    date: new Date(2020, 2, 2),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 50,
    name: "Angel Fish",
    picFolderName: "angel_fish",
    author: "Kamiya Satoshi",
    date: new Date(2020, 2, 5),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 51,
    name: "Gold Fish",
    picFolderName: "gold_fish",
    author: "Ta Trung Dong",
    date: new Date(2020, 2, 9),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 52,
    name: "Gourami",
    picFolderName: "gourami_fish",
    author: "Winston lee",
    date: new Date(2020, 2, 12),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 53,
    name: "Bird",
    picFolderName: "symbol",
    author: "Traditional",
    date: new Date(2020, 2, 16),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 54,
    name: "Narwhal",
    picFolderName: "narwhal",
    author: "Ryan Weish",
    date: new Date(2020, 2, 25),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 55,
    name: "ADT-X",
    picFolderName: "adt-x_plane",
    author: "Ryo Aoki",
    date: new Date(2020, 2, 27),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 3,
  },
  {
    id: 56,
    name: "Unicorn",
    picFolderName: "unicorn_2",
    author: "Tetsuya Gotani",
    date: new Date(2020, 3, 2),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.82,
    imagesCount: 2,
  },
  {
    id: 57,
    name: "Clown Fish",
    picFolderName: "clown_fish",
    author: "Yoo Tae Yong",
    date: new Date(2020, 3, 7),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 1,
  },
  {
    id: 58,
    name: "Toucan",
    picFolderName: "toucan",
    author: "Hoang Tien Quyet",
    date: new Date(2020, 3, 13),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 2,
  },
  {
    id: 59,
    name: "Squirrel",
    picFolderName: "squirrel",
    author: "Hideo Komatsu",
    date: new Date(2020, 3, 26),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 2,
  },
  {
    id: 60,
    name: "Man and Woman (Colored)",
    picFolderName: "man_and_woman_colored",
    author: "Sriram V",
    date: new Date(2020, 4, 5),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 3,
  },
  {
    id: 61,
    name: "Folded Structure",
    picFolderName: "structure",
    author: "Modern",
    date: new Date(2020, 4, 16),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 4,
  },
  {
    id: 62,
    name: "Siamese Fighting Fish",
    picFolderName: "siamese_fighting_fish",
    author: "Robert J. Lang",
    date: new Date(2020, 4, 21),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 2,
  },
  {
    id: 63,
    name: "F-15 Eagle",
    picFolderName: "f15_eagle",
    author: "Issei Yoshino",
    date: new Date(2020, 4, 29),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 6,
  },
  {
    id: 64,
    name: "T-Rex",
    picFolderName: "t-rex_2",
    author: "Takaya Inoue",
    date: new Date(2020, 5, 1),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 65,
    name: "Cockatiel",
    picFolderName: "cockatiel",
    author: "Soren Grinsfeider",
    date: new Date(2020, 5, 21),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.78,
    imagesCount: 1,
  },
  {
    id: 66,
    name: "Robin",
    picFolderName: "robin_2",
    author: "Dave Brill",
    date: new Date(2020, 5, 29),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 6,
  },
  {
    id: 67,
    name: "Long Tailed-Tit",
    picFolderName: "long_tailed_tit",
    author: "Kyohei Katsuta",
    date: new Date(2020, 6, 5),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 4,
  },
  {
    id: 68,
    name: "Lucifer",
    picFolderName: "lucifer",
    author: "Sriram V",
    date: new Date(2020, 6, 6),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 5,
    description:
      "The Morningstar meets\nthe detective eyes, they are—\nthe Devil's desire",
  },
  {
    id: 69,
    name: "Bird",
    picFolderName: "bird",
    author: "Kawahata Fumiaki",
    date: new Date(2020, 6, 10),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 5,
  },
  {
    id: 70,
    name: "Gojira",
    picFolderName: "gojira",
    author: "Seiji Nishikawa",
    date: new Date(2020, 6, 12),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 1,
    description:
      "From peacock to rose\nI sure was ready to fold—\nAsked for godzilla",
  },
  {
    id: 71,
    name: "Kiwi",
    picFolderName: "kiwi",
    author: "Roman Diaz",
    date: new Date(2020, 6, 14),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 3,
  },
  {
    id: 72,
    name: "Flying Boar",
    picFolderName: "flying_boar",
    author: "Mark Morden",
    date: new Date(2020, 6, 19),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.88,
    imagesCount: 1,
    description:
      "From bedrocks to our\nHearts, she could bend anything—\nLegacy of beifongs",
  },
  {
    id: 73,
    name: "Griffin",
    picFolderName: "griffin",
    author: "Kyohei Katsuta",
    date: new Date(2020, 6, 22),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.74,
    imagesCount: 2,
  },
  {
    id: 74,
    name: "Cerberus",
    picFolderName: "cerberus",
    author: "Henry Pham",
    date: new Date(2020, 6, 24),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.8,
    imagesCount: 5,
    description:
      "Watcher of the gates,\ngoodest boy of death’s domain—\npet of Lord Hades",
  },
  {
    id: 75,
    name: "Mouse",
    picFolderName: "mouse",
    author: "Zhen-Ming Huang",
    date: new Date(2020, 6, 31),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.83,
    imagesCount: 4,
  },
  {
    id: 76,
    name: "Lionhead Tamarin",
    picFolderName: "golden_tamarin",
    author: "Kunsulu Jilkishiyeva",
    date: new Date(2020, 7, 6),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.79,
    imagesCount: 4,
  },
  {
    id: 77,
    name: "Helicopter",
    picFolderName: "helicopter",
    author: "Marc Kirschenbaum",
    date: new Date(2020, 7, 8),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.71,
    imagesCount: 4,
  },
  {
    id: 78,
    name: "Airliner",
    picFolderName: "airliner",
    author: "Hitoshi Kakami",
    date: new Date(2020, 7, 11),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 6,
  },
  {
    id: 79,
    name: "Cat",
    picFolderName: "cat",
    author: "Ermakov Andrey",
    date: new Date(2020, 7, 17),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.79,
    imagesCount: 3,
  },
  {
    id: 80,
    name: "Gold Fish Type Square",
    picFolderName: "gold_fish_type_square",
    author: "Kasumi Seishi",
    date: new Date(2020, 7, 19),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 2,
  },
  {
    id: 81,
    name: "Sky Bison",
    picFolderName: "sky_bison",
    author: "Sriram V",
    date: new Date(2020, 7, 21),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.86,
    imagesCount: 8,
    description:
      "Helped me to be\nWith the rest of the clouds— my\nlittle Sky Bison",
  },
  {
    id: 82,
    name: "Sheep",
    picFolderName: "sheep",
    author: "Naoto Horiguchi",
    date: new Date(2020, 7, 23),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.78,
    imagesCount: 4,
  },
  {
    id: 83,
    name: "Peacock",
    picFolderName: "peacock_2",
    author: "Xiao Xian Huang",
    date: new Date(2020, 7, 27),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.61,
    imagesCount: 4,
  },
  {
    id: 84,
    name: "Pyramid",
    picFolderName: "pyramid",
    author: "Jo Nakashima",
    date: new Date(2020, 8, 1),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.77,
    imagesCount: 5,
  },
  {
    id: 85,
    name: "Exotic Bird",
    picFolderName: "exotic_bird",
    author: "Raphael Maillot",
    date: new Date(2020, 8, 5),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 2,
  },
  {
    id: 86,
    name: "Dodo",
    picFolderName: "dodo",
    author: "Kazuhiro Tominaga",
    date: new Date(2020, 8, 9),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.97,
    imagesCount: 3,
  },
  {
    id: 87,
    name: "Pomeranian",
    picFolderName: "pomeranian",
    author: "Kyohei Katsuta",
    date: new Date(2020, 8, 21),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.8,
    imagesCount: 5,
  },
  {
    id: 88,
    name: "Hippocampus",
    picFolderName: "hippocampus_2",
    author: "Hagiwara Gen",
    date: new Date(2020, 8, 27),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 89,
    name: "Centaur",
    picFolderName: "centaur",
    author: "Juston Hairgrove",
    date: new Date(2020, 9, 4),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 3,
  },
  {
    id: 90,
    name: "Galloping Horse",
    picFolderName: "running_horse",
    author: "Chen Xiao",
    date: new Date(2020, 9, 9),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.56,
    imagesCount: 5,
  },
  {
    id: 91,
    name: "Unicorn",
    picFolderName: "unicorn_3",
    author: "Yamamoto Taiga",
    date: new Date(2020, 9, 13),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.65,
    imagesCount: 6,
    description:
      "Through red mountains and\nBlue Valleys, crease pattern waits—\nFolded for first time",
  },
  {
    id: 92,
    name: "Horses Lineup",
    picFolderName: "horses_lineup_2",
    author: "Yamamoto Taiga, Juston Hairgrove, Hagiwara Gen, Chen Xiao",
    date: new Date(2020, 9, 16),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.74,
    imagesCount: 5,
  },
  {
    id: 93,
    name: "Folded Structure",
    picFolderName: "structure_2",
    author: "Modern",
    date: new Date(2020, 9, 23),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.77,
    imagesCount: 7,
  },
  {
    id: 94,
    name: "Thread-sail Filefish",
    picFolderName: "thread_sail_fish",
    author: "Kashiwamura Takuro",
    date: new Date(2020, 9, 26),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 1,
  },
  {
    id: 95,
    name: "Husky",
    picFolderName: "husky_dog",
    author: "Chen Xiao",
    date: new Date(2020, 9, 30),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.88,
    imagesCount: 1,
  },
  {
    id: 96,
    name: "Mermaid",
    picFolderName: "mermaid",
    author: "Chen Xiao",
    date: new Date(2020, 10, 1),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.9,
    imagesCount: 3,
  },
  {
    id: 97,
    name: "Nine Tailed Fox",
    picFolderName: "nine_tailed_fox",
    author: "Unknown",
    date: new Date(2020, 10, 6),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.52,
    imagesCount: 6,
    description:
      "Woman or machine,\nSpirit bound to hunt and guard— \nAlways the fox still",
  },
  {
    id: 98,
    name: "Black Knight",
    picFolderName: "horse_woman",
    author: "Chen Xiao",
    date: new Date(2020, 10, 15),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.73,
    imagesCount: 6,
    description:
      "In memory of\nHorse Woman, a Demon Knight— \nsaddle, magic, will",
  },
  {
    id: 99,
    name: "Succubus",
    picFolderName: "devil_girl",
    author: "Chen Xiao",
    date: new Date(2020, 10, 23),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 5,
  },
  {
    id: 100,
    name: "Elder Dragon",
    picFolderName: "elder_dragon",
    author: "Tsuruta Yoshimasa",
    date: new Date(2020, 10, 29),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.6,
    imagesCount: 9,
  },
  {
    id: 101,
    name: "Night Fury (Attempt 2)",
    picFolderName: "night_fury_2",
    author: "Saku B",
    date: new Date(2020, 11, 5),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.87,
    imagesCount: 10,
    description:
      "Unholy offspring\nof Lightning and Death itself—\na fold well deserved",
  },
  {
    id: 102,
    name: "Folded Structure",
    picFolderName: "structure_3",
    author: "Modern",
    date: new Date(2020, 11, 13),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.83,
    imagesCount: 7,
  },
  {
    id: 103,
    name: "Owl",
    picFolderName: "owl_2",
    author: "Seo Won Seon",
    date: new Date(2020, 11, 17),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.86,
    imagesCount: 4,
  },
  {
    id: 104,
    name: "Deer & Sleigh",
    picFolderName: "deer_and_sleigh",
    author: "Kamiya Satoshi, Hyo Ahn",
    date: new Date(2020, 11, 25),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.66,
    imagesCount: 6,
  },
  {
    id: 105,
    name: "Giraffe",
    picFolderName: "giraffe_2",
    author: "Seo Won Seon",
    date: new Date(2021, 0, 24),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.68,
    imagesCount: 2,
  },
  {
    id: 106,
    name: "Wolf",
    picFolderName: "wolf",
    author: "Meng Weining",
    date: new Date(2021, 1, 21),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 3,
  },
  {
    id: 107,
    name: "AH1 Cobra",
    picFolderName: "ah1_cobra",
    author: "Lee JaeGu",
    date: new Date(2021, 2, 28),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 108,
    name: "Sparrow",
    picFolderName: "sparrow",
    author: "Meng Weining",
    date: new Date(2021, 3, 14),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 3,
  },
  {
    id: 109,
    name: "Peacock",
    picFolderName: "peacock_3",
    author: "Meng Weining",
    date: new Date(2021, 4, 4),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.64,
    imagesCount: 4,
  },
  {
    id: 110,
    name: "Japanese Serow",
    picFolderName: "cow",
    author: "Kamiya Satoshi",
    date: new Date(2021, 4, 40),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.61,
    imagesCount: 2,
  },
  {
    id: 111,
    name: "Icarus",
    picFolderName: "icarus",
    author: "Takashi Hojyo",
    date: new Date(2021, 5, 6),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 6,
    description:
      "Tale of the wings which\nAlmost touched the top of clouds— \nThe fold's irony",
  },
  {
    id: 112,
    name: "Christmas Tree",
    picFolderName: "christmas_tree",
    author: "Sarjigami",
    date: new Date(2021, 11, 25),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.8,
    imagesCount: 1,
  },
  {
    id: 113,
    name: "Buddha",
    picFolderName: "buddha",
    author: "Takashi Hojyo",
    date: new Date(2023, 4, 6),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1.15,
    imagesCount: 2,
    description:
      "He too had desire\nof letting all desires go— \nthe contradiction",
  },
  {
    id: 114,
    name: "Camera",
    picFolderName: "camera",
    author: "Won Park",
    date: new Date(2023, 7, 28),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.75,
    imagesCount: 8,
  },
  {
    id: 115,
    name: "Alpaca",
    picFolderName: "alpaca",
    author: "Yuta Katsuzaki",
    date: new Date(2023, 9, 29),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 2,
  },
  {
    id: 116,
    name: "Frog",
    picFolderName: "frog",
    author: "Chris Heynan",
    date: new Date(2024, 6, 17),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 2,
  },
  {
    id: 117,
    name: "Monarch Butterfly",
    picFolderName: "monarch_butterfly",
    author: "Dang Viet Tan",
    date: new Date(2024, 6, 28),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
  {
    id: 118,
    name: "Flower Horn Fish",
    picFolderName: "flower_horn_fish",
    author: "Meng Weining",
    date: new Date(2024, 8, 8),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 0.89,
    imagesCount: 1,
  },
  {
    id: 119,
    name: "Crab",
    picFolderName: "crab",
    author: "Ivan Danny Handoko",
    date: new Date(2025, 1, 24),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 5,
  },
  {
    id: 120,
    name: "Fireworks",
    picFolderName: "firecracker",
    author: "Yami Yamauchi",
    date: new Date(2025, 2, 11),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 3,
  },
  {
    id: 121,
    name: "Dog",
    picFolderName: "dog",
    author: "Andrey Ermakov",
    date: new Date(2026, 0, 13),
    lastModifiedDate: "2026-01-15",
    heightWidthRatio: 1,
    imagesCount: 1,
  },
].reverse() as OrigamiInfo[];

export const origamiRoutes = ORIGAMI_INFO_ARRAY.map(
  (origami) => `/origami/${origami.picFolderName}`,
);

export const origamiLastMod = ORIGAMI_INFO_ARRAY.map((origami) => ({
  loc: `/origami/${origami.picFolderName}`,
  lastmod: origami.lastModifiedDate,
}));

export function findOrigamiByModelName(modelName: string) {
  return ORIGAMI_INFO_ARRAY.find(
    (origami) => origami.picFolderName === modelName,
  );
}
type OrigamiSeoMetaInput = Parameters<typeof useSeoMeta>[0];

export function createSeoMetaForOrigami(
  origami: OrigamiInfo,
): OrigamiSeoMetaInput {
  return {
    title: `Origami ${origami?.name} | Srira's Origami`,
    description: `Origami ${origami?.name} designed by ${origami?.author} folded by Sriram V on ${origami?.date.toDateString()}`,
    ogTitle: `Origami ${origami?.name} | Srira's Origami`,
    ogDescription: `Origami ${origami?.name} designed by ${origami?.author} folded by Sriram V on ${origami?.date.toDateString()}`,
  };
}

export function getOrigamiPositionedCards(
  columnCount: number,
  width: number,
  gap: number,
  infoHeight: number,
): PositionedOrigami[] {
  const columnHeights = Array(columnCount).fill(0);
  const positioned: PositionedOrigami[] = [];

  ORIGAMI_INFO_ARRAY.forEach((info, index) => {
    const column = index % columnCount;
    const heightPx = info.heightWidthRatio * width;
    const top = columnHeights[column];
    const left = column * (width + gap);

    positioned.push({ ...info, top, left });
    columnHeights[column] += heightPx + infoHeight + gap;
  });

  return positioned;
}
