export interface OrigamiInfo {
  id: number;
  name: string;
  picFolderName: string;
  author: string;
  date: Date;
  height: number;
}

export const ORIGAMI_INFO_ARRAY: OrigamiInfo[] = [
  {
    id: 1,
    name: "Deer and Fawn",
    picFolderName: "deer_and_fawn",
    author: "John Montroll, Stephen Weiss",
    date: new Date(2019, 5, 19),
    height: 185,
  },
  {
    id: 2,
    name: "Pegasus",
    picFolderName: "pegasus",
    author: "Dong Viet Thien",
    date: new Date(2019, 5, 25),
    height: 250,
  },
  {
    id: 3,
    name: "Owl",
    picFolderName: "owl",
    author: "Para Nicolas",
    date: new Date(2019, 5, 27),
    height: 250,
  },
  {
    id: 4,
    name: "Sea Turtle & Zebra",
    picFolderName: "turtle_and_zebra",
    author: "Won Park, Fumiaki Kawahata",
    date: new Date(2019, 5, 30),
    height: 250,
  },
  {
    id: 5,
    name: "Penguin",
    picFolderName: "penguin",
    author: "Yoo Tae Yong",
    date: new Date(2019, 6, 7),
    height: 250,
  },
  {
    id: 6,
    name: "Fighter Jets",
    picFolderName: "fighter_jets",
    author: "Won Park, Yoshihisa Kimura, Elmer A. Norvell",
    date: new Date(2019, 6, 10),
    height: 250,
  },
  {
    id: 7,
    name: "Coelophysis",
    picFolderName: "coelophysis",
    author: "Satoshi Kamiya",
    date: new Date(2019, 6, 11),
    height: 210,
  },
  {
    id: 8,
    name: "Baby Parrot",
    picFolderName: "baby_parrot",
    author: "Riccardo Foschi",
    date: new Date(2019, 6, 27),
    height: 250,
  },
  {
    id: 9,
    name: "Ant",
    picFolderName: "ant",
    author: "Piotr Pluta",
    date: new Date(2019, 6, 28),
    height: 250,
  },
  {
    id: 10,
    name: "Zero Fighter Plane",
    picFolderName: "zero_fighter_plane",
    author: "Won Park",
    date: new Date(2019, 7, 4),
    height: 189,
  },
  {
    id: 11,
    name: "Woman",
    picFolderName: "woman",
    author: "Sriram V",
    date: new Date(2019, 7, 7),
    height: 250,
  },
  {
    id: 12,
    name: "Night Fury",
    picFolderName: "night_fury",
    author: "Saku B",
    date: new Date(2019, 7, 12),
    height: 250,
  },
  {
    id: 13,
    name: "Man",
    picFolderName: "man",
    author: "Sriram V",
    date: new Date(2019, 7, 16),
    height: 250,
  },
  {
    id: 14,
    name: "Man & Woman",
    picFolderName: "man_and_woman",
    author: "Sriram V",
    date: new Date(2019, 7, 18),
    height: 250,
  },
  {
    id: 15,
    name: "Rooster",
    picFolderName: "rooster",
    author: "Gen Hagiwara",
    date: new Date(2019, 7, 25),
    height: 250,
  },
  {
    id: 16,
    name: "Daedalus",
    picFolderName: "daedalus",
    author: "Tran Trung Hieu",
    date: new Date(2019, 8, 1),
    height: 250,
  },
  {
    id: 17,
    name: "Peacock",
    picFolderName: "peacock",
    author: "Jun Maekawa",
    date: new Date(2019, 8, 1),
    height: 250,
  },
  {
    id: 18,
    name: "Mammoth",
    picFolderName: "mammoth",
    author: "Crease Lightning Origami",
    date: new Date(2019, 8, 2),
    height: 212,
  },
  {
    id: 19,
    name: "Dragon",
    picFolderName: "dragon",
    author: "Miyamoto Chuya",
    date: new Date(2019, 8, 8),
    height: 207,
  },
  {
    id: 20,
    name: "Robin",
    picFolderName: "robin",
    author: "Winston Lee",
    date: new Date(2019, 8, 9),
    height: 250,
  },
  {
    id: 21,
    name: "Rhinoceros",
    picFolderName: "rhino",
    author: "Ta Trung Dong",
    date: new Date(2019, 8, 13),
    height: 250,
  },
  {
    id: 22,
    name: "Lion",
    picFolderName: "lion",
    author: "Beth Johnson",
    date: new Date(2019, 8, 26),
    height: 250,
  },
  {
    id: 23,
    name: "Unicorn",
    picFolderName: "unicorn",
    author: "Roman Diaz",
    date: new Date(2019, 8, 29),
    height: 213,
  },
  {
    id: 24,
    name: "T-Rex",
    picFolderName: "t-rex",
    author: "Park Jong Woo",
    date: new Date(2019, 9, 3),
    height: 250,
  },
  {
    id: 25,
    name: "Horse",
    picFolderName: "horse",
    author: "Jeong Jae Il",
    date: new Date(2019, 9, 6),
    height: 250,
  },
  {
    id: 26,
    name: "Hippocampus",
    picFolderName: "hippocampus",
    author: "Roman Diaz",
    date: new Date(2019, 9, 8),
    height: 250,
  },
  {
    id: 27,
    name: "Horses Lineup",
    picFolderName: "horses_lineup",
    author: "Dong Viet Thien, Roman Diaz, Jeong Jae Il",
    date: new Date(2019, 9, 8),
    height: 188,
  },
].reverse();
